/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/workflow-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workflow definitions
         * @description Returns a paginated list of workflow definitions scoped to the caller's tenant.
         */
        get: operations["listWorkflowDefinitions"];
        put?: never;
        /**
         * Create a workflow definition
         * @description Creates a new workflow definition with an empty draft.
         */
        post: operations["createWorkflowDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a workflow definition
         * @description Returns the management resource for a single workflow definition.
         */
        get: operations["getWorkflowDefinition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-definitions/{id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update the draft
         * @description Replaces the mutable draft for a workflow definition. The request body
         *     carries the runtime definition and editor metadata separately. Clients
         *     should send `If-Match: "rev-<n>"` for optimistic concurrency.
         */
        put: operations["updateWorkflowDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-definitions/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate the current draft
         * @description Validates the current draft against the server-side node registry and
         *     returns diagnostics plus the canonical runtime hash.
         */
        post: operations["validateWorkflowDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-definitions/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a new version
         * @description Copies the current draft into an immutable version. Clients should send
         *     `If-Match: "rev-<n>"` to ensure they publish the draft they validated.
         */
        post: operations["publishWorkflowVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-definitions/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published versions
         * @description Returns a paginated list of published versions for a workflow definition.
         */
        get: operations["listWorkflowDefinitionVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-definitions/{id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a published version
         * @description Returns a single immutable published version.
         */
        get: operations["getWorkflowDefinitionVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow-definitions/{id}/versions/{version}/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invoke a published version
         * @description Starts an execution of the published version and returns the execution id.
         */
        post: operations["invokeWorkflowVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions/{executionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect an execution
         * @description Returns the current execution snapshot, including node statuses.
         */
        get: operations["getExecutionSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkflowDefinition: {
            /** Format: uuid */
            id: string;
            namespace: string;
            name: string;
            description?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy?: string;
            tenantId?: string;
            latestVersion?: string;
            draftRevision?: number;
        };
        WorkflowDefinitionList: {
            items: components["schemas"]["WorkflowDefinition"][];
            nextPageToken?: string;
        };
        CreateWorkflowDefinitionRequest: {
            namespace: string;
            name: string;
            description?: string;
        };
        WorkflowDraft: {
            definition: components["schemas"]["WorkflowDefinitionRuntime"];
            editorMetadata?: components["schemas"]["WorkflowEditorMetadata"];
            /** @description Per-definition monotonic integer for optimistic concurrency. */
            revision: number;
            /** @description Canonical runtime hash (runtime-sha256:v1:...). */
            definitionHash?: string;
            /** @description Full-definition audit hash (sha256:audit:v1:...). */
            auditFingerprint?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        WorkflowDefinitionVersion: {
            definition: components["schemas"]["WorkflowDefinitionRuntime"];
            editorMetadata?: components["schemas"]["WorkflowEditorMetadata"];
            revision: number;
            definitionHash?: string;
            auditFingerprint?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @description Client-supplied version string. */
            version: string;
            /** Format: date-time */
            publishedAt?: string;
            publishedBy?: string;
            immutable: boolean;
        };
        WorkflowDefinitionVersionList: {
            items: components["schemas"]["WorkflowDefinitionVersion"][];
            nextPageToken?: string;
        };
        PublishWorkflowVersionRequest: {
            version: string;
        };
        WorkflowDefinitionRuntime: {
            namespace: string;
            name: string;
            /** @description Optional runtime version tag (maps to WorkflowDef.Version). */
            versionTag?: string;
            /** @description Human documentation; excluded from the runtime hash. */
            description?: string;
            spec?: string;
            runnerSelector?: components["schemas"]["RunnerSelector"];
            context?: components["schemas"]["WorkflowContext"];
            settings?: components["schemas"]["WorkflowSettings"];
            options?: components["schemas"]["WorkflowOptions"];
            credentials?: {
                [key: string]: components["schemas"]["CredentialDef"];
            };
            params?: {
                [key: string]: components["schemas"]["ParamDef"];
            };
            node_templates?: {
                [key: string]: components["schemas"]["NodeTemplate"];
            };
            nodes?: components["schemas"]["RuntimeNodeDef"][];
            connections?: components["schemas"]["Connections"];
            outputs?: {
                [key: string]: components["schemas"]["WorkflowOutput"];
            };
            /** @description Runtime-semantic pinned node inputs. */
            pin_data?: {
                [key: string]: unknown;
            };
        };
        WorkflowEditorMetadata: {
            /** @description Map of node id/name to visual position. */
            positions?: {
                [key: string]: components["schemas"]["Position"];
            };
            viewport?: {
                x?: number;
                y?: number;
                zoom?: number;
            };
            /** @description Map of node id/name to UI overrides. */
            ui?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** @description Map of node id/name to author notes. */
            notes?: {
                [key: string]: string;
            };
            /** @description Read-only derived cache of WorkflowDefinitionRuntime.pin_data. */
            readonly pinData?: {
                [key: string]: unknown;
            };
        };
        RuntimeNodeDef: {
            name: string;
            type: string;
            kind?: components["schemas"]["NodeKind"];
            version?: number;
            template?: string;
            disabled?: boolean;
            on_error?: string;
            runnerSelector?: components["schemas"]["RunnerSelector"];
            inputs?: components["schemas"]["PortDecl"][];
            output_schema?: {
                [key: string]: unknown;
            };
            parameters?: {
                [key: string]: unknown;
            };
            retry?: components["schemas"]["RetrySettings"];
        };
        /** @enum {string} */
        NodeKind: "action" | "trigger";
        Position: {
            x?: number;
            y?: number;
        };
        PortDecl: {
            name: string;
            required?: boolean;
        };
        Connection: {
            node: string;
            input: string;
        };
        /** @description Map[source_node]map[output_port][]Connection(target). */
        Connections: {
            [key: string]: {
                [key: string]: components["schemas"]["Connection"][];
            };
        };
        WorkflowContext: {
            vars?: {
                [key: string]: unknown;
            };
            config?: {
                [key: string]: unknown;
            };
        };
        WorkflowSettings: {
            timeout?: number;
            concurrency?: number;
            timezone?: string;
            on_error?: string;
            pin_data_mode?: string;
            retry?: components["schemas"]["RetrySettings"];
        };
        RetrySettings: {
            enabled?: boolean;
            max_attempts?: number;
            strategy?: string;
            initial_interval?: number;
            max_interval?: number;
            multiplier?: number;
        };
        RunnerSelector: {
            mode?: components["schemas"]["RunnerSelectorMode"];
            matchLabels?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        RunnerSelectorMode: "default" | "required";
        WorkflowOptions: {
            allow_cycles?: boolean;
            max_auto_depth?: number;
            experimental_expand?: boolean;
        };
        CredentialDef: {
            name?: string;
            type?: string;
        };
        ParamDef: {
            type: string;
            required?: boolean;
            display_name?: string;
            default?: unknown;
            validation?: {
                [key: string]: unknown;
            };
        };
        NodeTemplate: {
            type?: string;
            parameters?: {
                [key: string]: unknown;
            };
        };
        WorkflowOutput: {
            value?: unknown;
            display_name?: string;
        };
        Diagnostic: {
            code: string;
            /** @enum {string} */
            severity: "error" | "warning" | "info";
            message: string;
            path?: string;
            nodeId?: string;
            connectionRef?: {
                node?: string;
                input?: string;
            };
        };
        ValidationResult: {
            valid: boolean;
            definitionHash?: string;
            diagnostics?: components["schemas"]["Diagnostic"][];
        };
        InvokeWorkflowRequest: {
            entry: string;
            input?: {
                [key: string]: unknown;
            };
        };
        InvokeWorkflowResponse: {
            executionId: string;
        };
        ExecutionSnapshot: {
            id: string;
            status: components["schemas"]["ExecutionStatus"];
            params?: Record<string, never>;
            nodeStatuses?: {
                [key: string]: components["schemas"]["NodeStatus"];
            };
            parentId?: string;
            traceId?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        /** @enum {string} */
        ExecutionStatus: "pending" | "running" | "success" | "failed" | "canceling" | "canceled" | "timeout";
        /** @enum {string} */
        NodeStatus: "pending" | "running" | "committing" | "success" | "failed" | "skipped" | "suspended" | "continued" | "canceled" | "waiting";
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Error response. */
        DefaultError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Stable workflow definition UUID. */
        WorkflowDefinitionId: string;
        /** @description Client-supplied version string. */
        Version: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listWorkflowDefinitions: {
        parameters: {
            query?: {
                pageToken?: string;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of workflow definitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionList"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
    createWorkflowDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowDefinitionRequest"];
            };
        };
        responses: {
            /** @description Workflow definition created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
    getWorkflowDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable workflow definition UUID. */
                id: components["parameters"]["WorkflowDefinitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow definition resource. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
    updateWorkflowDraft: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                /** @description Stable workflow definition UUID. */
                id: components["parameters"]["WorkflowDefinitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDraft"];
            };
        };
        responses: {
            /** @description Updated draft. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDraft"];
                };
            };
            412: components["responses"]["DefaultError"];
            default: components["responses"]["DefaultError"];
        };
    };
    validateWorkflowDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable workflow definition UUID. */
                id: components["parameters"]["WorkflowDefinitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
    publishWorkflowVersion: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                /** @description Stable workflow definition UUID. */
                id: components["parameters"]["WorkflowDefinitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishWorkflowVersionRequest"];
            };
        };
        responses: {
            /** @description Published version. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionVersion"];
                };
            };
            412: components["responses"]["DefaultError"];
            default: components["responses"]["DefaultError"];
        };
    };
    listWorkflowDefinitionVersions: {
        parameters: {
            query?: {
                pageToken?: string;
                pageSize?: number;
            };
            header?: never;
            path: {
                /** @description Stable workflow definition UUID. */
                id: components["parameters"]["WorkflowDefinitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionVersionList"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
    getWorkflowDefinitionVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable workflow definition UUID. */
                id: components["parameters"]["WorkflowDefinitionId"];
                /** @description Client-supplied version string. */
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionVersion"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
    invokeWorkflowVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable workflow definition UUID. */
                id: components["parameters"]["WorkflowDefinitionId"];
                /** @description Client-supplied version string. */
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvokeWorkflowRequest"];
            };
        };
        responses: {
            /** @description Execution accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvokeWorkflowResponse"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
    getExecutionSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable execution UUID. */
                executionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionSnapshot"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
}
