// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: service/protocol/runnerpb/runner.proto

package runnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	NodeVersion   int32                  `protobuf:"varint,2,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *Capability) GetNodeVersion() int32 {
	if x != nil {
		return x.NodeVersion
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Concurrency   int32                  `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Capabilities  []*Capability          `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RegisterRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *RegisterRequest) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	InFlight      int32                  `protobuf:"varint,3,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *HeartbeatRequest) GetInFlight() int32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type PollTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Capabilities  []*Capability          `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskRequest) Reset() {
	*x = PollTaskRequest{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskRequest) ProtoMessage() {}

func (x *PollTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskRequest.ProtoReflect.Descriptor instead.
func (*PollTaskRequest) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{5}
}

func (x *PollTaskRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *PollTaskRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *PollTaskRequest) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PollTaskRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type PollTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lease_json is the JSON-encoded engine.TaskLease, empty when no task is
	// available.
	LeaseJson []byte `protobuf:"bytes,1,opt,name=lease_json,json=leaseJson,proto3" json:"lease_json,omitempty"`
	// wait_nanos is how long the runner should wait before polling again when no
	// lease is returned.
	WaitNanos     int64 `protobuf:"varint,2,opt,name=wait_nanos,json=waitNanos,proto3" json:"wait_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskResponse) Reset() {
	*x = PollTaskResponse{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskResponse) ProtoMessage() {}

func (x *PollTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskResponse.ProtoReflect.Descriptor instead.
func (*PollTaskResponse) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{6}
}

func (x *PollTaskResponse) GetLeaseJson() []byte {
	if x != nil {
		return x.LeaseJson
	}
	return nil
}

func (x *PollTaskResponse) GetWaitNanos() int64 {
	if x != nil {
		return x.WaitNanos
	}
	return 0
}

type ReportResultRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RunnerId string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	// lease_json is the JSON-encoded engine.TaskLease the result belongs to.
	LeaseJson []byte `protobuf:"bytes,2,opt,name=lease_json,json=leaseJson,proto3" json:"lease_json,omitempty"`
	// result_json is the JSON-encoded protocol task result.
	ResultJson    []byte `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{7}
}

func (x *ReportResultRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *ReportResultRequest) GetLeaseJson() []byte {
	if x != nil {
		return x.LeaseJson
	}
	return nil
}

func (x *ReportResultRequest) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_service_protocol_runnerpb_runner_proto protoreflect.FileDescriptor

const file_service_protocol_runnerpb_runner_proto_rawDesc = "" +
	"\n" +
	"&service/protocol/runnerpb/runner.proto\x12\x0fxflow.runner.v1\"L\n" +
	"\n" +
	"Capability\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x12!\n" +
	"\fnode_version\x18\x02 \x01(\x05R\vnodeVersion\"\x92\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x05R\vconcurrency\x12?\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x1b.xflow.runner.v1.CapabilityR\fcapabilities\x12D\n" +
	"\x06labels\x18\x04 \x03(\v2,.xflow.runner.v1.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\"\x86\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x1b\n" +
	"\tin_flight\x18\x03 \x01(\x05R\binFlight\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"4\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"\x8c\x02\n" +
	"\x0fPollTaskRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12?\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x1b.xflow.runner.v1.CapabilityR\fcapabilities\x12D\n" +
	"\x06labels\x18\x04 \x03(\v2,.xflow.runner.v1.PollTaskRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x10PollTaskResponse\x12\x1d\n" +
	"\n" +
	"lease_json\x18\x01 \x01(\fR\tleaseJson\x12\x1d\n" +
	"\n" +
	"wait_nanos\x18\x02 \x01(\x03R\twaitNanos\"r\n" +
	"\x13ReportResultRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1d\n" +
	"\n" +
	"lease_json\x18\x02 \x01(\fR\tleaseJson\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\"H\n" +
	"\x14ReportResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xe3\x02\n" +
	"\x0eRunnerProtocol\x12O\n" +
	"\bRegister\x12 .xflow.runner.v1.RegisterRequest\x1a!.xflow.runner.v1.RegisterResponse\x12R\n" +
	"\tHeartbeat\x12!.xflow.runner.v1.HeartbeatRequest\x1a\".xflow.runner.v1.HeartbeatResponse\x12O\n" +
	"\bPollTask\x12 .xflow.runner.v1.PollTaskRequest\x1a!.xflow.runner.v1.PollTaskResponse\x12[\n" +
	"\fReportResult\x12$.xflow.runner.v1.ReportResultRequest\x1a%.xflow.runner.v1.ReportResultResponseB2Z0github.com/xbcio/xflow/service/protocol/runnerpbb\x06proto3"

var (
	file_service_protocol_runnerpb_runner_proto_rawDescOnce sync.Once
	file_service_protocol_runnerpb_runner_proto_rawDescData []byte
)

func file_service_protocol_runnerpb_runner_proto_rawDescGZIP() []byte {
	file_service_protocol_runnerpb_runner_proto_rawDescOnce.Do(func() {
		file_service_protocol_runnerpb_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_protocol_runnerpb_runner_proto_rawDesc), len(file_service_protocol_runnerpb_runner_proto_rawDesc)))
	})
	return file_service_protocol_runnerpb_runner_proto_rawDescData
}

var file_service_protocol_runnerpb_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_service_protocol_runnerpb_runner_proto_goTypes = []any{
	(*Capability)(nil),           // 0: xflow.runner.v1.Capability
	(*RegisterRequest)(nil),      // 1: xflow.runner.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 2: xflow.runner.v1.RegisterResponse
	(*HeartbeatRequest)(nil),     // 3: xflow.runner.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 4: xflow.runner.v1.HeartbeatResponse
	(*PollTaskRequest)(nil),      // 5: xflow.runner.v1.PollTaskRequest
	(*PollTaskResponse)(nil),     // 6: xflow.runner.v1.PollTaskResponse
	(*ReportResultRequest)(nil),  // 7: xflow.runner.v1.ReportResultRequest
	(*ReportResultResponse)(nil), // 8: xflow.runner.v1.ReportResultResponse
	nil,                          // 9: xflow.runner.v1.RegisterRequest.LabelsEntry
	nil,                          // 10: xflow.runner.v1.PollTaskRequest.LabelsEntry
}
var file_service_protocol_runnerpb_runner_proto_depIdxs = []int32{
	0,  // 0: xflow.runner.v1.RegisterRequest.capabilities:type_name -> xflow.runner.v1.Capability
	9,  // 1: xflow.runner.v1.RegisterRequest.labels:type_name -> xflow.runner.v1.RegisterRequest.LabelsEntry
	0,  // 2: xflow.runner.v1.PollTaskRequest.capabilities:type_name -> xflow.runner.v1.Capability
	10, // 3: xflow.runner.v1.PollTaskRequest.labels:type_name -> xflow.runner.v1.PollTaskRequest.LabelsEntry
	1,  // 4: xflow.runner.v1.RunnerProtocol.Register:input_type -> xflow.runner.v1.RegisterRequest
	3,  // 5: xflow.runner.v1.RunnerProtocol.Heartbeat:input_type -> xflow.runner.v1.HeartbeatRequest
	5,  // 6: xflow.runner.v1.RunnerProtocol.PollTask:input_type -> xflow.runner.v1.PollTaskRequest
	7,  // 7: xflow.runner.v1.RunnerProtocol.ReportResult:input_type -> xflow.runner.v1.ReportResultRequest
	2,  // 8: xflow.runner.v1.RunnerProtocol.Register:output_type -> xflow.runner.v1.RegisterResponse
	4,  // 9: xflow.runner.v1.RunnerProtocol.Heartbeat:output_type -> xflow.runner.v1.HeartbeatResponse
	6,  // 10: xflow.runner.v1.RunnerProtocol.PollTask:output_type -> xflow.runner.v1.PollTaskResponse
	8,  // 11: xflow.runner.v1.RunnerProtocol.ReportResult:output_type -> xflow.runner.v1.ReportResultResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_service_protocol_runnerpb_runner_proto_init() }
func file_service_protocol_runnerpb_runner_proto_init() {
	if File_service_protocol_runnerpb_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_protocol_runnerpb_runner_proto_rawDesc), len(file_service_protocol_runnerpb_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_protocol_runnerpb_runner_proto_goTypes,
		DependencyIndexes: file_service_protocol_runnerpb_runner_proto_depIdxs,
		MessageInfos:      file_service_protocol_runnerpb_runner_proto_msgTypes,
	}.Build()
	File_service_protocol_runnerpb_runner_proto = out.File
	file_service_protocol_runnerpb_runner_proto_goTypes = nil
	file_service_protocol_runnerpb_runner_proto_depIdxs = nil
}
