// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: service/protocol/runnerpb/runner.proto

package runnerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerProtocol_Register_FullMethodName     = "/xflow.runner.v1.RunnerProtocol/Register"
	RunnerProtocol_Heartbeat_FullMethodName    = "/xflow.runner.v1.RunnerProtocol/Heartbeat"
	RunnerProtocol_PollTask_FullMethodName     = "/xflow.runner.v1.RunnerProtocol/PollTask"
	RunnerProtocol_ReportResult_FullMethodName = "/xflow.runner.v1.RunnerProtocol/ReportResult"
)

// RunnerProtocolClient is the client API for RunnerProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunnerProtocol is the control-plane <-> execution-plane contract. It mirrors
// the HTTP+JSON Runner Protocol one RPC per endpoint so a runner can switch
// transports without changing its execution loop.
//
// Rich domain payloads (TaskLease, TaskResult) are carried as JSON bytes rather
// than mirrored field-by-field: they embed map[string]any / any structures that
// round-trip cleanly through the engine's existing, tested JSON codecs but map
// poorly onto protobuf. Scalar control fields stay typed for cross-language and
// validation friendliness.
type RunnerProtocolClient interface {
	// Register announces a runner and its capabilities to the server.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat reports runner capacity and liveness.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// PollTask long-polls for one assigned task lease. The response carries an
	// empty lease and a wait hint when nothing is available.
	PollTask(ctx context.Context, in *PollTaskRequest, opts ...grpc.CallOption) (*PollTaskResponse, error)
	// ReportResult commits a finished task result back to the server.
	ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*ReportResultResponse, error)
}

type runnerProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerProtocolClient(cc grpc.ClientConnInterface) RunnerProtocolClient {
	return &runnerProtocolClient{cc}
}

func (c *runnerProtocolClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, RunnerProtocol_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerProtocolClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, RunnerProtocol_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerProtocolClient) PollTask(ctx context.Context, in *PollTaskRequest, opts ...grpc.CallOption) (*PollTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollTaskResponse)
	err := c.cc.Invoke(ctx, RunnerProtocol_PollTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerProtocolClient) ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*ReportResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResultResponse)
	err := c.cc.Invoke(ctx, RunnerProtocol_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerProtocolServer is the server API for RunnerProtocol service.
// All implementations must embed UnimplementedRunnerProtocolServer
// for forward compatibility.
//
// RunnerProtocol is the control-plane <-> execution-plane contract. It mirrors
// the HTTP+JSON Runner Protocol one RPC per endpoint so a runner can switch
// transports without changing its execution loop.
//
// Rich domain payloads (TaskLease, TaskResult) are carried as JSON bytes rather
// than mirrored field-by-field: they embed map[string]any / any structures that
// round-trip cleanly through the engine's existing, tested JSON codecs but map
// poorly onto protobuf. Scalar control fields stay typed for cross-language and
// validation friendliness.
type RunnerProtocolServer interface {
	// Register announces a runner and its capabilities to the server.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat reports runner capacity and liveness.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// PollTask long-polls for one assigned task lease. The response carries an
	// empty lease and a wait hint when nothing is available.
	PollTask(context.Context, *PollTaskRequest) (*PollTaskResponse, error)
	// ReportResult commits a finished task result back to the server.
	ReportResult(context.Context, *ReportResultRequest) (*ReportResultResponse, error)
	mustEmbedUnimplementedRunnerProtocolServer()
}

// UnimplementedRunnerProtocolServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerProtocolServer struct{}

func (UnimplementedRunnerProtocolServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRunnerProtocolServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedRunnerProtocolServer) PollTask(context.Context, *PollTaskRequest) (*PollTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollTask not implemented")
}
func (UnimplementedRunnerProtocolServer) ReportResult(context.Context, *ReportResultRequest) (*ReportResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedRunnerProtocolServer) mustEmbedUnimplementedRunnerProtocolServer() {}
func (UnimplementedRunnerProtocolServer) testEmbeddedByValue()                        {}

// UnsafeRunnerProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerProtocolServer will
// result in compilation errors.
type UnsafeRunnerProtocolServer interface {
	mustEmbedUnimplementedRunnerProtocolServer()
}

func RegisterRunnerProtocolServer(s grpc.ServiceRegistrar, srv RunnerProtocolServer) {
	// If the following call panics, it indicates UnimplementedRunnerProtocolServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerProtocol_ServiceDesc, srv)
}

func _RunnerProtocol_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerProtocolServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerProtocol_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerProtocolServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerProtocol_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerProtocolServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerProtocol_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerProtocolServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerProtocol_PollTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerProtocolServer).PollTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerProtocol_PollTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerProtocolServer).PollTask(ctx, req.(*PollTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerProtocol_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerProtocolServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerProtocol_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerProtocolServer).ReportResult(ctx, req.(*ReportResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerProtocol_ServiceDesc is the grpc.ServiceDesc for RunnerProtocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerProtocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xflow.runner.v1.RunnerProtocol",
	HandlerType: (*RunnerProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RunnerProtocol_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _RunnerProtocol_Heartbeat_Handler,
		},
		{
			MethodName: "PollTask",
			Handler:    _RunnerProtocol_PollTask_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _RunnerProtocol_ReportResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/protocol/runnerpb/runner.proto",
}
