// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: service/protocol/runnerpb/runner.proto

package runnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	NodeVersion   int32                  `protobuf:"varint,2,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *Capability) GetNodeVersion() int32 {
	if x != nil {
		return x.NodeVersion
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Concurrency   int32                  `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Capabilities  []*Capability          `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tenants       []string               `protobuf:"bytes,5,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RegisterRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *RegisterRequest) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetTenants() []string {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	InFlight      int32                  `protobuf:"varint,3,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *HeartbeatRequest) GetInFlight() int32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type PollTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Capabilities  []*Capability          `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskRequest) Reset() {
	*x = PollTaskRequest{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskRequest) ProtoMessage() {}

func (x *PollTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskRequest.ProtoReflect.Descriptor instead.
func (*PollTaskRequest) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{5}
}

func (x *PollTaskRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *PollTaskRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *PollTaskRequest) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PollTaskRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PollTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PollTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lease_json is the JSON-encoded engine.TaskLease, empty when no task is
	// available.
	LeaseJson []byte `protobuf:"bytes,1,opt,name=lease_json,json=leaseJson,proto3" json:"lease_json,omitempty"`
	// wait_nanos is how long the runner should wait before polling again when no
	// lease is returned.
	WaitNanos     int64 `protobuf:"varint,2,opt,name=wait_nanos,json=waitNanos,proto3" json:"wait_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskResponse) Reset() {
	*x = PollTaskResponse{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskResponse) ProtoMessage() {}

func (x *PollTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskResponse.ProtoReflect.Descriptor instead.
func (*PollTaskResponse) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{6}
}

func (x *PollTaskResponse) GetLeaseJson() []byte {
	if x != nil {
		return x.LeaseJson
	}
	return nil
}

func (x *PollTaskResponse) GetWaitNanos() int64 {
	if x != nil {
		return x.WaitNanos
	}
	return 0
}

type ReportResultRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RunnerId string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	// lease_json is the JSON-encoded engine.TaskLease the result belongs to.
	LeaseJson []byte `protobuf:"bytes,2,opt,name=lease_json,json=leaseJson,proto3" json:"lease_json,omitempty"`
	// result_json is the JSON-encoded protocol task result.
	ResultJson []byte `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	SessionId  string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// trace_carrier carries W3C traceparent/tracestate headers injected by the
	// runner from its xflow.task.execute span so the server's report/commit span
	// is parented to the runner's execute span (real W3C remote parent, not a
	// trace_id/span_id string reconstruction). Additive map field; older peers
	// that do not populate it simply leave it empty and the server falls back to
	// the lease's dispatch carrier.
	TraceCarrier  map[string]string `protobuf:"bytes,5,rep,name=trace_carrier,json=traceCarrier,proto3" json:"trace_carrier,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{7}
}

func (x *ReportResultRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *ReportResultRequest) GetLeaseJson() []byte {
	if x != nil {
		return x.LeaseJson
	}
	return nil
}

func (x *ReportResultRequest) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *ReportResultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportResultRequest) GetTraceCarrier() map[string]string {
	if x != nil {
		return x.TraceCarrier
	}
	return nil
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RunnerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*RunnerFrame_Hello
	//	*RunnerFrame_Result
	//	*RunnerFrame_Bye
	Frame         isRunnerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerFrame) Reset() {
	*x = RunnerFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerFrame) ProtoMessage() {}

func (x *RunnerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerFrame.ProtoReflect.Descriptor instead.
func (*RunnerFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{9}
}

func (x *RunnerFrame) GetFrame() isRunnerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *RunnerFrame) GetHello() *HelloFrame {
	if x != nil {
		if x, ok := x.Frame.(*RunnerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *RunnerFrame) GetResult() *ResultFrame {
	if x != nil {
		if x, ok := x.Frame.(*RunnerFrame_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *RunnerFrame) GetBye() *ByeFrame {
	if x != nil {
		if x, ok := x.Frame.(*RunnerFrame_Bye); ok {
			return x.Bye
		}
	}
	return nil
}

type isRunnerFrame_Frame interface {
	isRunnerFrame_Frame()
}

type RunnerFrame_Hello struct {
	Hello *HelloFrame `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type RunnerFrame_Result struct {
	Result *ResultFrame `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type RunnerFrame_Bye struct {
	Bye *ByeFrame `protobuf:"bytes,3,opt,name=bye,proto3,oneof"`
}

func (*RunnerFrame_Hello) isRunnerFrame_Frame() {}

func (*RunnerFrame_Result) isRunnerFrame_Frame() {}

func (*RunnerFrame_Bye) isRunnerFrame_Frame() {}

type HelloFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Concurrency   int32                  `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Capabilities  []*Capability          `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tenants       []string               `protobuf:"bytes,5,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloFrame) Reset() {
	*x = HelloFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloFrame) ProtoMessage() {}

func (x *HelloFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloFrame.ProtoReflect.Descriptor instead.
func (*HelloFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{10}
}

func (x *HelloFrame) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *HelloFrame) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *HelloFrame) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HelloFrame) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *HelloFrame) GetTenants() []string {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type ResultFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseJson     []byte                 `protobuf:"bytes,2,opt,name=lease_json,json=leaseJson,proto3" json:"lease_json,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultFrame) Reset() {
	*x = ResultFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultFrame) ProtoMessage() {}

func (x *ResultFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultFrame.ProtoReflect.Descriptor instead.
func (*ResultFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{11}
}

func (x *ResultFrame) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ResultFrame) GetLeaseJson() []byte {
	if x != nil {
		return x.LeaseJson
	}
	return nil
}

func (x *ResultFrame) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type ByeFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByeFrame) Reset() {
	*x = ByeFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByeFrame) ProtoMessage() {}

func (x *ByeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByeFrame.ProtoReflect.Descriptor instead.
func (*ByeFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{12}
}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ServerFrame_Welcome
	//	*ServerFrame_Task
	//	*ServerFrame_Ack
	//	*ServerFrame_Backoff
	//	*ServerFrame_Keepalive
	Frame         isServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{13}
}

func (x *ServerFrame) GetFrame() isServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ServerFrame) GetWelcome() *WelcomeFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerFrame) GetTask() *TaskFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *ServerFrame) GetAck() *AckFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerFrame) GetBackoff() *BackoffFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Backoff); ok {
			return x.Backoff
		}
	}
	return nil
}

func (x *ServerFrame) GetKeepalive() *KeepaliveFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Keepalive); ok {
			return x.Keepalive
		}
	}
	return nil
}

type isServerFrame_Frame interface {
	isServerFrame_Frame()
}

type ServerFrame_Welcome struct {
	Welcome *WelcomeFrame `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerFrame_Task struct {
	Task *TaskFrame `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

type ServerFrame_Ack struct {
	Ack *AckFrame `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type ServerFrame_Backoff struct {
	Backoff *BackoffFrame `protobuf:"bytes,4,opt,name=backoff,proto3,oneof"`
}

type ServerFrame_Keepalive struct {
	Keepalive *KeepaliveFrame `protobuf:"bytes,5,opt,name=keepalive,proto3,oneof"`
}

func (*ServerFrame_Welcome) isServerFrame_Frame() {}

func (*ServerFrame_Task) isServerFrame_Frame() {}

func (*ServerFrame_Ack) isServerFrame_Frame() {}

func (*ServerFrame_Backoff) isServerFrame_Frame() {}

func (*ServerFrame_Keepalive) isServerFrame_Frame() {}

type WelcomeFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeFrame) Reset() {
	*x = WelcomeFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeFrame) ProtoMessage() {}

func (x *WelcomeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeFrame.ProtoReflect.Descriptor instead.
func (*WelcomeFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{14}
}

func (x *WelcomeFrame) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *WelcomeFrame) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type TaskFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseJson     []byte                 `protobuf:"bytes,1,opt,name=lease_json,json=leaseJson,proto3" json:"lease_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFrame) Reset() {
	*x = TaskFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFrame) ProtoMessage() {}

func (x *TaskFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFrame.ProtoReflect.Descriptor instead.
func (*TaskFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{15}
}

func (x *TaskFrame) GetLeaseJson() []byte {
	if x != nil {
		return x.LeaseJson
	}
	return nil
}

type AckFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckFrame) Reset() {
	*x = AckFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckFrame) ProtoMessage() {}

func (x *AckFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckFrame.ProtoReflect.Descriptor instead.
func (*AckFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{16}
}

func (x *AckFrame) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *AckFrame) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AckFrame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BackoffFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaitNanos     int64                  `protobuf:"varint,1,opt,name=wait_nanos,json=waitNanos,proto3" json:"wait_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackoffFrame) Reset() {
	*x = BackoffFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackoffFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackoffFrame) ProtoMessage() {}

func (x *BackoffFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackoffFrame.ProtoReflect.Descriptor instead.
func (*BackoffFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{17}
}

func (x *BackoffFrame) GetWaitNanos() int64 {
	if x != nil {
		return x.WaitNanos
	}
	return 0
}

type KeepaliveFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveFrame) Reset() {
	*x = KeepaliveFrame{}
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveFrame) ProtoMessage() {}

func (x *KeepaliveFrame) ProtoReflect() protoreflect.Message {
	mi := &file_service_protocol_runnerpb_runner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveFrame.ProtoReflect.Descriptor instead.
func (*KeepaliveFrame) Descriptor() ([]byte, []int) {
	return file_service_protocol_runnerpb_runner_proto_rawDescGZIP(), []int{18}
}

var File_service_protocol_runnerpb_runner_proto protoreflect.FileDescriptor

const file_service_protocol_runnerpb_runner_proto_rawDesc = "" +
	"\n" +
	"&service/protocol/runnerpb/runner.proto\x12\x0fxflow.runner.v1\"L\n" +
	"\n" +
	"Capability\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x12!\n" +
	"\fnode_version\x18\x02 \x01(\x05R\vnodeVersion\"\xac\x02\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x05R\vconcurrency\x12?\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x1b.xflow.runner.v1.CapabilityR\fcapabilities\x12D\n" +
	"\x06labels\x18\x04 \x03(\v2,.xflow.runner.v1.RegisterRequest.LabelsEntryR\x06labels\x12\x18\n" +
	"\atenants\x18\x05 \x03(\tR\atenants\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xa5\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x1b\n" +
	"\tin_flight\x18\x03 \x01(\x05R\binFlight\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"4\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"\xab\x02\n" +
	"\x0fPollTaskRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12?\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x1b.xflow.runner.v1.CapabilityR\fcapabilities\x12D\n" +
	"\x06labels\x18\x04 \x03(\v2,.xflow.runner.v1.PollTaskRequest.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x10PollTaskResponse\x12\x1d\n" +
	"\n" +
	"lease_json\x18\x01 \x01(\fR\tleaseJson\x12\x1d\n" +
	"\n" +
	"wait_nanos\x18\x02 \x01(\x03R\twaitNanos\"\xaf\x02\n" +
	"\x13ReportResultRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1d\n" +
	"\n" +
	"lease_json\x18\x02 \x01(\fR\tleaseJson\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12[\n" +
	"\rtrace_carrier\x18\x05 \x03(\v26.xflow.runner.v1.ReportResultRequest.TraceCarrierEntryR\ftraceCarrier\x1a?\n" +
	"\x11TraceCarrierEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x14ReportResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb2\x01\n" +
	"\vRunnerFrame\x123\n" +
	"\x05hello\x18\x01 \x01(\v2\x1b.xflow.runner.v1.HelloFrameH\x00R\x05hello\x126\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.xflow.runner.v1.ResultFrameH\x00R\x06result\x12-\n" +
	"\x03bye\x18\x03 \x01(\v2\x19.xflow.runner.v1.ByeFrameH\x00R\x03byeB\a\n" +
	"\x05frame\"\xa2\x02\n" +
	"\n" +
	"HelloFrame\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x05R\vconcurrency\x12?\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x1b.xflow.runner.v1.CapabilityR\fcapabilities\x12?\n" +
	"\x06labels\x18\x04 \x03(\v2'.xflow.runner.v1.HelloFrame.LabelsEntryR\x06labels\x12\x18\n" +
	"\atenants\x18\x05 \x03(\tR\atenants\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\vResultFrame\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1d\n" +
	"\n" +
	"lease_json\x18\x02 \x01(\fR\tleaseJson\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\"\n" +
	"\n" +
	"\bByeFrame\"\xae\x02\n" +
	"\vServerFrame\x129\n" +
	"\awelcome\x18\x01 \x01(\v2\x1d.xflow.runner.v1.WelcomeFrameH\x00R\awelcome\x120\n" +
	"\x04task\x18\x02 \x01(\v2\x1a.xflow.runner.v1.TaskFrameH\x00R\x04task\x12-\n" +
	"\x03ack\x18\x03 \x01(\v2\x19.xflow.runner.v1.AckFrameH\x00R\x03ack\x129\n" +
	"\abackoff\x18\x04 \x01(\v2\x1d.xflow.runner.v1.BackoffFrameH\x00R\abackoff\x12?\n" +
	"\tkeepalive\x18\x05 \x01(\v2\x1f.xflow.runner.v1.KeepaliveFrameH\x00R\tkeepaliveB\a\n" +
	"\x05frame\"L\n" +
	"\fWelcomeFrame\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"*\n" +
	"\tTaskFrame\x12\x1d\n" +
	"\n" +
	"lease_json\x18\x01 \x01(\fR\tleaseJson\"W\n" +
	"\bAckFrame\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"-\n" +
	"\fBackoffFrame\x12\x1d\n" +
	"\n" +
	"wait_nanos\x18\x01 \x01(\x03R\twaitNanos\"\x10\n" +
	"\x0eKeepaliveFrame2\xae\x03\n" +
	"\x0eRunnerProtocol\x12I\n" +
	"\aConnect\x12\x1c.xflow.runner.v1.RunnerFrame\x1a\x1c.xflow.runner.v1.ServerFrame(\x010\x01\x12O\n" +
	"\bRegister\x12 .xflow.runner.v1.RegisterRequest\x1a!.xflow.runner.v1.RegisterResponse\x12R\n" +
	"\tHeartbeat\x12!.xflow.runner.v1.HeartbeatRequest\x1a\".xflow.runner.v1.HeartbeatResponse\x12O\n" +
	"\bPollTask\x12 .xflow.runner.v1.PollTaskRequest\x1a!.xflow.runner.v1.PollTaskResponse\x12[\n" +
	"\fReportResult\x12$.xflow.runner.v1.ReportResultRequest\x1a%.xflow.runner.v1.ReportResultResponseB2Z0github.com/xbcio/xflow/service/protocol/runnerpbb\x06proto3"

var (
	file_service_protocol_runnerpb_runner_proto_rawDescOnce sync.Once
	file_service_protocol_runnerpb_runner_proto_rawDescData []byte
)

func file_service_protocol_runnerpb_runner_proto_rawDescGZIP() []byte {
	file_service_protocol_runnerpb_runner_proto_rawDescOnce.Do(func() {
		file_service_protocol_runnerpb_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_protocol_runnerpb_runner_proto_rawDesc), len(file_service_protocol_runnerpb_runner_proto_rawDesc)))
	})
	return file_service_protocol_runnerpb_runner_proto_rawDescData
}

var file_service_protocol_runnerpb_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_service_protocol_runnerpb_runner_proto_goTypes = []any{
	(*Capability)(nil),           // 0: xflow.runner.v1.Capability
	(*RegisterRequest)(nil),      // 1: xflow.runner.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 2: xflow.runner.v1.RegisterResponse
	(*HeartbeatRequest)(nil),     // 3: xflow.runner.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 4: xflow.runner.v1.HeartbeatResponse
	(*PollTaskRequest)(nil),      // 5: xflow.runner.v1.PollTaskRequest
	(*PollTaskResponse)(nil),     // 6: xflow.runner.v1.PollTaskResponse
	(*ReportResultRequest)(nil),  // 7: xflow.runner.v1.ReportResultRequest
	(*ReportResultResponse)(nil), // 8: xflow.runner.v1.ReportResultResponse
	(*RunnerFrame)(nil),          // 9: xflow.runner.v1.RunnerFrame
	(*HelloFrame)(nil),           // 10: xflow.runner.v1.HelloFrame
	(*ResultFrame)(nil),          // 11: xflow.runner.v1.ResultFrame
	(*ByeFrame)(nil),             // 12: xflow.runner.v1.ByeFrame
	(*ServerFrame)(nil),          // 13: xflow.runner.v1.ServerFrame
	(*WelcomeFrame)(nil),         // 14: xflow.runner.v1.WelcomeFrame
	(*TaskFrame)(nil),            // 15: xflow.runner.v1.TaskFrame
	(*AckFrame)(nil),             // 16: xflow.runner.v1.AckFrame
	(*BackoffFrame)(nil),         // 17: xflow.runner.v1.BackoffFrame
	(*KeepaliveFrame)(nil),       // 18: xflow.runner.v1.KeepaliveFrame
	nil,                          // 19: xflow.runner.v1.RegisterRequest.LabelsEntry
	nil,                          // 20: xflow.runner.v1.PollTaskRequest.LabelsEntry
	nil,                          // 21: xflow.runner.v1.ReportResultRequest.TraceCarrierEntry
	nil,                          // 22: xflow.runner.v1.HelloFrame.LabelsEntry
}
var file_service_protocol_runnerpb_runner_proto_depIdxs = []int32{
	0,  // 0: xflow.runner.v1.RegisterRequest.capabilities:type_name -> xflow.runner.v1.Capability
	19, // 1: xflow.runner.v1.RegisterRequest.labels:type_name -> xflow.runner.v1.RegisterRequest.LabelsEntry
	0,  // 2: xflow.runner.v1.PollTaskRequest.capabilities:type_name -> xflow.runner.v1.Capability
	20, // 3: xflow.runner.v1.PollTaskRequest.labels:type_name -> xflow.runner.v1.PollTaskRequest.LabelsEntry
	21, // 4: xflow.runner.v1.ReportResultRequest.trace_carrier:type_name -> xflow.runner.v1.ReportResultRequest.TraceCarrierEntry
	10, // 5: xflow.runner.v1.RunnerFrame.hello:type_name -> xflow.runner.v1.HelloFrame
	11, // 6: xflow.runner.v1.RunnerFrame.result:type_name -> xflow.runner.v1.ResultFrame
	12, // 7: xflow.runner.v1.RunnerFrame.bye:type_name -> xflow.runner.v1.ByeFrame
	0,  // 8: xflow.runner.v1.HelloFrame.capabilities:type_name -> xflow.runner.v1.Capability
	22, // 9: xflow.runner.v1.HelloFrame.labels:type_name -> xflow.runner.v1.HelloFrame.LabelsEntry
	14, // 10: xflow.runner.v1.ServerFrame.welcome:type_name -> xflow.runner.v1.WelcomeFrame
	15, // 11: xflow.runner.v1.ServerFrame.task:type_name -> xflow.runner.v1.TaskFrame
	16, // 12: xflow.runner.v1.ServerFrame.ack:type_name -> xflow.runner.v1.AckFrame
	17, // 13: xflow.runner.v1.ServerFrame.backoff:type_name -> xflow.runner.v1.BackoffFrame
	18, // 14: xflow.runner.v1.ServerFrame.keepalive:type_name -> xflow.runner.v1.KeepaliveFrame
	9,  // 15: xflow.runner.v1.RunnerProtocol.Connect:input_type -> xflow.runner.v1.RunnerFrame
	1,  // 16: xflow.runner.v1.RunnerProtocol.Register:input_type -> xflow.runner.v1.RegisterRequest
	3,  // 17: xflow.runner.v1.RunnerProtocol.Heartbeat:input_type -> xflow.runner.v1.HeartbeatRequest
	5,  // 18: xflow.runner.v1.RunnerProtocol.PollTask:input_type -> xflow.runner.v1.PollTaskRequest
	7,  // 19: xflow.runner.v1.RunnerProtocol.ReportResult:input_type -> xflow.runner.v1.ReportResultRequest
	13, // 20: xflow.runner.v1.RunnerProtocol.Connect:output_type -> xflow.runner.v1.ServerFrame
	2,  // 21: xflow.runner.v1.RunnerProtocol.Register:output_type -> xflow.runner.v1.RegisterResponse
	4,  // 22: xflow.runner.v1.RunnerProtocol.Heartbeat:output_type -> xflow.runner.v1.HeartbeatResponse
	6,  // 23: xflow.runner.v1.RunnerProtocol.PollTask:output_type -> xflow.runner.v1.PollTaskResponse
	8,  // 24: xflow.runner.v1.RunnerProtocol.ReportResult:output_type -> xflow.runner.v1.ReportResultResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_service_protocol_runnerpb_runner_proto_init() }
func file_service_protocol_runnerpb_runner_proto_init() {
	if File_service_protocol_runnerpb_runner_proto != nil {
		return
	}
	file_service_protocol_runnerpb_runner_proto_msgTypes[9].OneofWrappers = []any{
		(*RunnerFrame_Hello)(nil),
		(*RunnerFrame_Result)(nil),
		(*RunnerFrame_Bye)(nil),
	}
	file_service_protocol_runnerpb_runner_proto_msgTypes[13].OneofWrappers = []any{
		(*ServerFrame_Welcome)(nil),
		(*ServerFrame_Task)(nil),
		(*ServerFrame_Ack)(nil),
		(*ServerFrame_Backoff)(nil),
		(*ServerFrame_Keepalive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_protocol_runnerpb_runner_proto_rawDesc), len(file_service_protocol_runnerpb_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_protocol_runnerpb_runner_proto_goTypes,
		DependencyIndexes: file_service_protocol_runnerpb_runner_proto_depIdxs,
		MessageInfos:      file_service_protocol_runnerpb_runner_proto_msgTypes,
	}.Build()
	File_service_protocol_runnerpb_runner_proto = out.File
	file_service_protocol_runnerpb_runner_proto_goTypes = nil
	file_service_protocol_runnerpb_runner_proto_depIdxs = nil
}
